# Chapter 6: Other computer vision problems

In [2]:
! pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 719.8/719.8 kB 26.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.1/124.1 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.9/246.9 kB 16.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 45.8 MB/s eta 0:00:00:00:01

In [3]:
from fastai.vision.all import *
from fastbook import *

In [35]:
def list_methods(var):
    return [a for a in dir(var) if callable(getattr(var, a))]

## Part 1: Multi-label data

### Block 1: Multi-label vs. single-label: when labels aren't mutually exclusive

In some datasets, data metadata is stored in a csv file that specifies, among other things, where the actual data files live. The PASCAL dataset falls into this category, and that's what we're using for this chapter.

In [11]:
path = untar_data(URLs.PASCAL_2007)
path

```html
<div>
<progress max="1637796771" value="1637801984"></progress> 100.00% [1637801984/1637796771 01:55&lt;00:00]</div>

```

Path('/root/.fastai/data/pascal_2007')

In [12]:
Path.BASE_PATH = path
path.ls()

[Path('test.json'), Path('train.csv'), Path('test'), Path('valid.json'), Path('train'), Path('test.csv'), Path('segmentation'), Path('train.json')]

Notice the `train.csv` and `test.csv` files.

In [13]:
(path/'train').ls()

(#5012) [Path('train/009528.jpg'), Path('train/009721.jpg'), Path('train/006269.jpg'), Path('train/007762.jpg'), Path('train/001586.jpg'), Path('train/004846.jpg'), Path('train/006628.jpg'), Path('train/007899.jpg'), Path('train/001981.jpg'), Path('train/008722.jpg'), Path('train/000030.jpg'), Path('train/004955.jpg'), Path('train/005421.jpg'), Path('train/005230.jpg'), Path('train/007330.jpg'), Path('train/002411.jpg'), Path('train/003658.jpg'), Path('train/002657.jpg'), Path('train/008398.jpg'), Path('train/000777.jpg'), Path('train/004244.jpg'), Path('train/003063.jpg'), Path('train/000009.jpg'), Path('train/009809.jpg'), Path('train/001231.jpg'), Path('train/009654.jpg'), Path('train/006802.jpg'), Path('train/009792.jpg'), Path('train/004185.jpg'), Path('train/008468.jpg'), Path('train/001517.jpg'), Path('train/001521.jpg'), Path('train/004196.jpg'), Path('train/007606.jpg'), Path('train/006983.jpg'), Path('train/009022.jpg'), Path('train/009443.jpg'), Path('train/003859.jpg'), Path('train/004201.jpg'), Path('train/000917.jpg'), Path('train/000477.jpg'), Path('train/002737.jpg'), Path('train/005531.jpg'), Path('train/003635.jpg'), Path('train/000461.jpg'), Path('train/007329.jpg'), Path('train/003159.jpg'), Path('train/003162.jpg'), Path('train/004737.jpg'), Path('train/008105.jpg'), Path('train/008606.jpg'), Path('train/002095.jpg'), Path('train/004867.jpg'), Path('train/009790.jpg'), Path('train/005582.jpg'), Path('train/004470.jpg'), Path('train/004693.jpg'), Path('train/008293.jpg'), Path('train/001494.jpg'), Path('train/007565.jpg'), Path('train/002102.jpg'), Path('train/007898.jpg'), Path('train/004537.jpg'), Path('train/002281.jpg'), Path('train/007694.jpg'), Path('train/001612.jpg'), Path('train/001490.jpg'), Path('train/004588.jpg'), Path('train/009670.jpg'), Path('train/006337.jpg'), Path('train/003847.jpg'), Path('train/005794.jpg'), Path('train/005014.jpg'), Path('train/002259.jpg'), Path('train/008467.jpg'), Path('train/005773.jpg'), Path('train/009851.jpg'), Path('train/004368.jpg'), Path('train/002975.jpg'), Path('train/002308.jpg'), Path('train/008381.jpg'), Path('train/003207.jpg'), Path('train/000209.jpg'), Path('train/002362.jpg'), Path('train/002117.jpg'), Path('train/005346.jpg'), Path('train/008098.jpg'), Path('train/008017.jpg'), Path('train/000926.jpg'), Path('train/004882.jpg'), Path('train/002947.jpg'), Path('train/006009.jpg'), Path('train/006472.jpg'), Path('train/001402.jpg'), Path('train/008226.jpg'), Path('train/007089.jpg'), Path('train/009691.jpg'), Path('train/007411.jpg'), Path('train/009138.jpg'), Path('train/008665.jpg'), Path('train/009842.jpg'), Path('train/002913.jpg'), Path('train/006862.jpg'), Path('train/009189.jpg'), Path('train/003818.jpg'), Path('train/006000.jpg'), Path('train/008710.jpg'), Path('train/003415.jpg'), Path('train/004371.jpg'), Path('train/006707.jpg'), Path('train/002867.jpg'), Path('train/006520.jpg'), Path('train/004897.jpg'), Path('train/006922.jpg'), Path('train/005144.jpg'), Path('train/005037.jpg'), Path('train/000236.jpg'), Path('train/005864.jpg'), Path('train/001995.jpg'), Path('train/001618.jpg'), Path('train/001101.jpg'), Path('train/006411.jpg'), Path('train/006176.jpg'), Path('train/005662.jpg'), Path('train/000525.jpg'), Path('train/006708.jpg'), Path('train/000559.jpg'), Path('train/002045.jpg'), Path('train/001184.jpg'), Path('train/006704.jpg'), Path('train/009208.jpg'), Path('train/007919.jpg'), Path('train/003622.jpg'), Path('train/003214.jpg'), Path('train/004010.jpg'), Path('train/002547.jpg'), Path('train/004003.jpg'), Path('train/005071.jpg'), Path('train/004990.jpg'), Path('train/009738.jpg'), Path('train/000469.jpg'), Path('train/004694.jpg'), Path('train/003077.jpg'), Path('train/002810.jpg'), Path('train/007376.jpg'), Path('train/004878.jpg'), Path('train/001298.jpg'), Path('train/009724.jpg'), Path('train/008872.jpg'), Path('train/009318.jpg'), Path('train/004263.jpg'), Path('train/005735.jpg'), Path('train/002114.jpg'), Path('train/002094.jpg'), Path('train/006766.jpg'), Path('train/006794.jpg'), Path('train/009432.jpg'), Path('train/001733.jpg'), Path('train/005805.jpg'), Path('train/006436.jpg'), Path('train/000180.jpg'), Path('train/003748.jpg'), Path('train/001604.jpg'), Path('train/002627.jpg'), Path('train/009488.jpg'), Path('train/001056.jpg'), Path('train/000962.jpg'), Path('train/004259.jpg'), Path('train/004468.jpg'), Path('train/004452.jpg'), Path('train/001651.jpg'), Path('train/001661.jpg'), Path('train/002064.jpg'), Path('train/000095.jpg'), Path('train/003028.jpg'), Path('train/009816.jpg'), Path('train/005685.jpg'), Path('train/005600.jpg'), Path('train/006859.jpg'), Path('train/002480.jpg'), Path('train/005718.jpg'), Path('train/005064.jpg'), Path('train/001284.jpg'), Path('train/006392.jpg'), Path('train/003717.jpg'), Path('train/000193.jpg'), Path('train/006952.jpg'), Path('train/009551.jpg'), Path('train/003421.jpg'), Path('train/002899.jpg'), Path('train/009961.jpg'), Path('train/009032.jpg'), Path('train/002373.jpg'), Path('train/003007.jpg'), Path('train/009781.jpg'), Path('train/009623.jpg'), Path('train/002962.jpg'), Path('train/003262.jpg'), Path('train/005258.jpg'), Path('train/002816.jpg'), Path('train/008871.jpg'), Path('train/008813.jpg'), Path('train/003960.jpg'), Path('train/007633.jpg'), Path('train/009459.jpg'), Path('train/004257.jpg'), Path('train/007300.jpg'), Path('train/006931.jpg'), Path('train/002387.jpg'), Path('train/001726.jpg'), Path('train/009278.jpg'), Path('train/000500.jpg'), Path('train/001247.jpg'), Path('train/001315.jpg'), Path('train/004656.jpg'), Path('train/001532.jpg'), Path('train/006699.jpg'), Path('train/009166.jpg'), Path('train/000710.jpg'), Path('train/007809.jpg'), Path('train/008416.jpg'), Path('train/008069.jpg'), Path('train/001024.jpg'), Path('train/003614.jpg'), Path('train/003784.jpg'), Path('train/005779.jpg'), Path('train/008067.jpg'), Path('train/008061.jpg'), Path('train/002241.jpg'), Path('train/003161.jpg'), Path('train/002924.jpg'), Path('train/008251.jpg'), Path('train/003935.jpg'), Path('train/003759.jpg'), Path('train/009920.jpg'), Path('train/003636.jpg'), Path('train/008610.jpg'), Path('train/007974.jpg'), Path('train/006456.jpg'), Path('train/009860.jpg'), Path('train/006011.jpg'), Path('train/007200.jpg'), Path('train/005654.jpg'), Path('train/004519.jpg'), Path('train/005365.jpg'), Path('train/009151.jpg'), Path('train/009618.jpg'), Path('train/001541.jpg'), Path('train/004532.jpg'), Path('train/001497.jpg')...]

To better understand the data, we need to look at the contents of the CSV files. For that we'll use pandas.

In [14]:
import pandas as pd

In [49]:
train = pd.read_csv((path/'train.csv'))
train

           fname          labels  is_valid
0     000005.jpg           chair      True
1     000007.jpg             car      True
2     000009.jpg    horse person      True
3     000012.jpg             car     False
4     000016.jpg         bicycle      True
...          ...             ...       ...
5006  009954.jpg    horse person      True
5007  009955.jpg            boat      True
5008  009958.jpg  person bicycle      True
5009  009959.jpg             car     False
5010  009961.jpg             dog     False

[5011 rows x 3 columns]

The columns are clear:
- `fname` is the filename
- `labels` tells us the labels for the image; we can see that a space-separated list of values indicates that there are multiple appropriate labels for an image
- `is_valid` indicates whether the image should be in the training or validation set

Let's find the rows that have multiple labels.

In [43]:
train[train['labels'].str.contains(' ')]

           fname             labels  is_valid
2     000009.jpg       horse person      True
5     000017.jpg       person horse     False
8     000021.jpg         dog person      True
9     000023.jpg     bicycle person     False
12    000030.jpg     bicycle person      True
...          ...                ...       ...
5003  009947.jpg        boat person      True
5004  009949.jpg  sofa chair person     False
5005  009950.jpg       train person      True
5006  009954.jpg       horse person      True
5008  009958.jpg     person bicycle      True

[2203 rows x 3 columns]

So a little less than half of the rows have multiple labels.